USE [master]
GO

/****** Object:  Database [MushroomPP]    Script Date: 01/04/2021 19.33.02 ******/
CREATE DATABASE [MushroomPP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MushroomPP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MushroomPP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MushroomPP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MushroomPP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MushroomPP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MushroomPP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MushroomPP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MushroomPP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MushroomPP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MushroomPP] SET ARITHABORT OFF 
GO

ALTER DATABASE [MushroomPP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MushroomPP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MushroomPP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MushroomPP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MushroomPP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MushroomPP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MushroomPP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MushroomPP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MushroomPP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MushroomPP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MushroomPP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MushroomPP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MushroomPP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MushroomPP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MushroomPP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MushroomPP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MushroomPP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MushroomPP] SET RECOVERY FULL 
GO

ALTER DATABASE [MushroomPP] SET  MULTI_USER 
GO

ALTER DATABASE [MushroomPP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MushroomPP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MushroomPP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MushroomPP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MushroomPP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MushroomPP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MushroomPP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MushroomPP] SET  READ_WRITE 
GO

