USE MushroomPP
GO

CREATE SCHEMA [main]
GO

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 01-Apr-2021 19.37.44 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE main.[_hardware]
(
	[hardware_key] int IDENTITY (1, 1) NOT NULL,
	[hardware_id] nvarchar(32) NOT NULL,
	[last_update] datetime NULL,
	[current_air_temperature] real NULL,
	[current_air_humidity] real NULL,
	[current_air_co2] real NULL,
	[desired_air_humidity] real NULL,
	[user_key] int NOT NULL
)
GO

CREATE TABLE main.[_mushroom_stage]
(
	[stage_key] int IDENTITY (1, 1) NOT NULL,
	[stage_name] nvarchar(32) NOT NULL
)
GO

CREATE TABLE main.[_mushroom_type]
(
	[type_key] int IDENTITY (1, 1) NOT NULL,
	[type_name] nvarchar(32) NOT NULL
)
GO

CREATE TABLE main.[_sensor_entry]
(
	[entry_key] int IDENTITY (1, 1) NOT NULL,
	[entry_time] datetime NOT NULL,
	[air_temperature] real NOT NULL,
	[air_humidity] real NOT NULL,
	[air_co2] real NOT NULL,
	[desired_air_humidity] real NULL,
	[specimen_key] int NULL
)
GO

CREATE TABLE main.[_specimen]
(
	[specimen_key] int IDENTITY (1, 1) NOT NULL,
	[planted_date] datetime NOT NULL,
	[discraded_date] datetime NULL,
	[specimen_name] nvarchar(32) NOT NULL,
	[specimen_description] nvarchar(256) NOT NULL,
	[desired_air_humidity] real NULL,
	[type_key] int NOT NULL,
	[hardware_key] int NULL
)
GO

CREATE TABLE main.[_status_entry]
(
	[entry_key] int IDENTITY (1, 1) NOT NULL,
	[entry_time] datetime NOT NULL,
	[stage_key] int NOT NULL,
	[specimen_key] int NOT NULL
)
GO

CREATE TABLE main.[_user]
(
	[user_key] int IDENTITY (1, 1) NOT NULL,
	[username] nvarchar(32) NOT NULL,
	[password_hashed] nvarchar(64) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE main.[_hardware] 
 ADD CONSTRAINT [PK_hardware]
	PRIMARY KEY CLUSTERED ([hardware_key] ASC)
GO

ALTER TABLE main.[_hardware] 
 ADD CONSTRAINT [hardware_id] UNIQUE NONCLUSTERED ([hardware_id] ASC)
GO

ALTER TABLE main.[_mushroom_stage] 
 ADD CONSTRAINT [PK_mushroom_stage]
	PRIMARY KEY CLUSTERED ([stage_key] ASC)
GO

ALTER TABLE main.[_mushroom_stage] 
 ADD CONSTRAINT [mushroom_stage] UNIQUE NONCLUSTERED ([stage_name] ASC)
GO

ALTER TABLE main.[_mushroom_type] 
 ADD CONSTRAINT [PK_mushroom_type]
	PRIMARY KEY CLUSTERED ([type_key] ASC)
GO

ALTER TABLE main.[_mushroom_type] 
 ADD CONSTRAINT [mushroom_type] UNIQUE NONCLUSTERED ([type_name] ASC)
GO

ALTER TABLE main.[_sensor_entry] 
 ADD CONSTRAINT [PK_sensor_entry]
	PRIMARY KEY CLUSTERED ([entry_key] ASC)
GO

ALTER TABLE main.[_specimen] 
 ADD CONSTRAINT [PK_specimen]
	PRIMARY KEY CLUSTERED ([specimen_key] ASC)
GO

ALTER TABLE main.[_status_entry] 
 ADD CONSTRAINT [PK_status_entry]
	PRIMARY KEY CLUSTERED ([entry_key] ASC)
GO

ALTER TABLE main.[_user] 
 ADD CONSTRAINT [PK_user]
	PRIMARY KEY CLUSTERED ([user_key] ASC)
GO

ALTER TABLE main.[_user] 
 ADD CONSTRAINT [username] UNIQUE NONCLUSTERED ([username] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE main.[_hardware] ADD CONSTRAINT [FK_hardware_user]
	FOREIGN KEY ([user_key]) REFERENCES main.[_user] ([user_key]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE main.[_sensor_entry] ADD CONSTRAINT [FK_sensor_entry_specimen]
	FOREIGN KEY ([specimen_key]) REFERENCES main.[_specimen] ([specimen_key]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE main.[_specimen] ADD CONSTRAINT [FK_specimen_hardware]
	FOREIGN KEY ([hardware_key]) REFERENCES main.[_hardware] ([hardware_key]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE main.[_specimen] ADD CONSTRAINT [FK_specimen_mushroom_type]
	FOREIGN KEY ([type_key]) REFERENCES main.[_mushroom_type] ([type_key]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE main.[_status_entry] ADD CONSTRAINT [FK_status_entry_mushroom_stage]
	FOREIGN KEY ([stage_key]) REFERENCES main.[_mushroom_stage] ([stage_key]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE main.[_status_entry] ADD CONSTRAINT [FK_status_entry_specimen]
	FOREIGN KEY ([specimen_key]) REFERENCES main.[_specimen] ([specimen_key]) ON DELETE No Action ON UPDATE No Action
GO